baseURL = "/blog.erlware.org/"
languageCode = "en-us"
title = "Erlware Blog"
theme = "casper-two"
publishDir = "docs"

[params]
  title       = "Erlware Blog"
  subtitle    = "Erlang tools and packaging"

  githubName = "erlware"

  logo = "img/logo.png"


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200


[[menu.main]]
  name = "About"
  url = "/about"
  weight = 100
